selinux: avoid 64-bit division of inode numbers
As reported by Arnd, a previous change to convert the selinuxfs inode
numbers to u64 to match the rest of the kernel caused a problem on 32-bit
systems:

  arm-linux-gnueabi-ld: .../selinuxfs.o: in function `sel_read_class':
   selinuxfs.c:(.text+0xdcc): undefined reference to `__aeabi_uldivmod'
  arm-linux-gnueabi-ld: .../selinuxfs.o: in function `sel_read_perm':
   selinuxfs.c:(.text+0xed0): undefined reference to `__aeabi_uldivmod'

Since we don't currently use more than 24-bits in the selinuxfs inodes
(see SEL_INO_MASK), fix this by applying the SEL_INO_MASK to the
selinuxfs inode numbers and casting to a u32 before performing any
division operations.

Fixes: fc68b6a45f16 ("selinux: convert selinuxfs inode numbers from unsigned long to u64")
Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Paul Moore <paul@paul-moore.com>